---
title: C28125 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: bd9a17d781ba106e20512aaff1c46ba0952cb9cf
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77265761"
---
# <a name="c28125"></a>C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

ADVERTENCIA C28125: se debe llamar a la función desde un bloque try/except  
  
 El controlador está llamando a una función a la que se debe llamar desde dentro de un bloque try/except, como [ProbeForRead](https://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](https://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](https://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Ejemplo  
 El siguiente código de ejemplo genera esta advertencia:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 El siguiente código de ejemplo evita esta advertencia:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```
