---
title: C6320 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 1d37a8d33f756372cd0448e94cf9f6d5e2408cf1
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 09/02/2020
ms.locfileid: "77273425"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

ADVERTENCIA C6320: la expresión de filtro de excepciones es la constante EXCEPTION_EXECUTE_HANDLER. Esto puede enmascarar excepciones que no se han diseñado para ser controladas  
  
 Esta advertencia indica el efecto secundario de utilizar EXCEPTION_EXECUTE_HANDLER constante en __except bloque. En este caso, la instrucción del \_ bloque _except siempre se ejecutará para controlar la excepción, incluidas las excepciones que no desea administrar en una función determinada. Se recomienda que Compruebe la excepción antes de controlarla.  
  
## <a name="example"></a>Ejemplo  
 El código siguiente genera esta advertencia porque el bloque __except intentará controlar las excepciones de todos los tipos:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Para corregir esta advertencia, use `GetExceptionCode` para comprobar si hay una excepción determinada antes de controlarla, tal y como se muestra en el código siguiente:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Consulte también  
 [try-except (Instrucción)](https://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)
