---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 87c5a405a47bd35e82d971b078141fbad4c4b250
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77270052"
---
# <a name="c28163"></a>C28163
ADVERTENCIA C28163: nunca se debe llamar a la función desde un bloque try/except

 Esta advertencia se indica cuando una función es de un tipo que nunca se debe incluir en un bloque de `try/except` se encuentra en un bloque de `try/except`. La herramienta de análisis de código encontró al menos una ruta de acceso en la que la función llamada estaba dentro de un bloque `try/except`.
