---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 03552bd5990b2533ad6632bbe86776d21afe32ee
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878143"
---
# <a name="c6312"></a>C6312
Advertencia C6312: Posible bucle infinito: se utilizará la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepciones de try-except

 Esta advertencia indica el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como-1) en la expresión de filtro de un controlador de excepciones estructurado. El uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podría provocar un bucle infinito. Por ejemplo, si el hardware ha generado una excepción, se reiniciará la instrucción que produjo la excepción. Si la dirección que causó la excepción sigue siendo incorrecta, se producirá otra excepción y se controlará de la misma manera. Esto produce un bucle infinito.

 Una llamada explícita a `RaiseException` no producirá directamente un bucle infinito, pero seguirá la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si se usaba `RaiseException` para evitar desreferenciar un puntero no válido.

 Normalmente, solo se debe devolver `EXCEPTION_CONTINUE_EXECUTION` por una función llamada en la expresión de filtro, que tiene la oportunidad de corregir el puntero que produjo la excepción o la memoria subyacente.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
